---
- name: Create ftp directory in /etc/skel
  ansible.builtin.file:
    path: /etc/skel/ftp
    owner: root
    group: root
    state: directory
    mode: '0710'
- name: Debug
  ansible.builtin.debug:
    msg: "{{ tf_username }}"
- name: Debug password hash 
  ansible.builtin.debug:
    msg: "{{ tf_password_hash }}"
- name: Debug pubkey
  ansible.builtin.debug:
    msg: "{{ tf_user_pubkey }}"
- name: Create a user
  ansible.builtin.user:
    name: "{{ tf_username }}"
    create_home: true
    shell: "/usr/bin/bash"
    password: "{{ tf_password_hash }}"
    state: present
- name: Add SSH authorized key
  ansible.posix.authorized_key:
    user: "{{ tf_username }}"
    state: "present"
    key: "{{ tf_user_pubkey }}"
- name: Edit sshd config
  ansible.builtin.copy:
    src: sshd_config    
    dest: /etc/ssh/sshd_config
    group: root
    owner: root
    mode: '0640'

